# Generated by Django 2.2.6 on 2019-11-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
        migrations.CreateModel(
            name='StudentProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Guitarra/Violao'), (1, 'Violino'), (2, 'Sopro'), (3, 'Piano/Teclado')])),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
            options={
                'verbose_name': 'StudentProfessor',
                'verbose_name_plural': 'StudentProfessors',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='professors',
            field=models.ManyToManyField(related_name='students', through='school.StudentProfessor', to='school.Professor'),
        ),
    ]
