# Generated by Django 2.2.6 on 2019-11-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfTheWeek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.DayOfTheWeek')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Time')),
            ],
        ),
    ]
