# Generated by Django 2.2.6 on 2019-11-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_schedulestudentprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoftheweek',
            name='time',
            field=models.ManyToManyField(related_name='dayOfTheWeeks', through='school.Schedule', to='school.Time'),
        ),
        migrations.AddField(
            model_name='time',
            name='dayOfTheWeek',
            field=models.ManyToManyField(related_name='times', through='school.Schedule', to='school.DayOfTheWeek'),
        ),
    ]
