# Generated by Django 2.2.6 on 2019-11-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='horary',
            field=models.TimeField(),
        ),
    ]
