# Generated by Django 2.2.6 on 2019-11-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20191113_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dayOfTheWeek',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=50),
        ),
    ]
