# Generated by Django 2.2.6 on 2019-11-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20191118_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoftheweek',
            name='time',
        ),
        migrations.RemoveField(
            model_name='time',
            name='dayOfTheWeek',
        ),
    ]
