# Generated by Django 2.2.6 on 2019-11-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20191119_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='dayOftheWeeks',
            field=models.ManyToManyField(related_name='times', through='school.Schedule', to='school.DayOfTheWeek'),
        ),
    ]
