# Generated by Django 2.2.6 on 2019-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20191119_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='dayOftheWeeks',
        ),
        migrations.AddField(
            model_name='student',
            name='schedules',
            field=models.ManyToManyField(related_name='students', through='school.ScheduleStudentProfessor', to='school.Schedule'),
        ),
    ]
