# Generated by Django 2.2.6 on 2019-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20191120_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='schedules',
        ),
        migrations.AlterField(
            model_name='student',
            name='professors',
            field=models.ManyToManyField(related_name='students', through='school.ScheduleStudentProfessor', to='school.Professor'),
        ),
    ]
