# Generated by Django 2.2.6 on 2019-11-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20191121_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestudentprofessor',
            name='role',
            field=models.IntegerField(choices=[(0, 'Guitarra/Violao'), (1, 'Violino'), (2, 'Sopro'), (3, 'Piano/Teclado')], default=0),
            preserve_default=False,
        ),
    ]
